Yozumina frontend
pbzweihander/chamsae pull request #26
Opened 2024-06-04 14:49 UTC by Squarecat-meow

add: image preview before upload, upload thumbnail in chirp bubble
add dependencies: React-redux, @reduxjs/toolkit
edit: chirp component into bottom component

2024-06-05 07:57 UTC, pbzweihander requested changes
redux가 꼭 필요할까요...? 꼭 state management를 외부 의존성 껴서 해야한다면 차라리 jotai라던가... 그리고 package.json이랑 yarn.lock 파일이 커밋이 안 되어있어요!

2024-06-05 07:58 UTC, pbzweihander requested changes

2024-06-05 07:58 UTC, pbzweihander commented on frontend/src/components/RightNavUpload.tsx
> +                </svg>
이건 어떤 아이콘인가요? 웬만하면 heroicon으로 통일하고, heroicon이 의존성에 들어있으니 그걸 직접 썼으면 좋겠어요.

2024-06-05 07:58 UTC, pbzweihander commented
react hook form을 떼버릴까 고민 중... (사유: 티르 님이 쓰지말라고함)

2024-06-23 15:09 UTC, Squarecat-meow commented on frontend/src/components/RightNavUpload.tsx
> +                </svg>
네 저건 이미지 미리보기 안에 있던 사진 아이콘이었는데 Heroicon에도 들어있었네요! 수정했습니다!

2024-06-23 15:13 UTC, Squarecat-meow commented
> redux가 꼭 필요할까요...? 꼭 state management를 외부 의존성 껴서 해야한다면 차라리 jotai라던가... 그리고 package.json이랑 yarn.lock 파일이 커밋이 안 되어있어요!

아무래도 리덕스가 무겁긴 하죠...? 전역 상태관리를 페이지 단위로 바꾸고자 한다면 jotai나 recoil이 알맞을지도 모르겠네요!

2024-06-23 16:13 UTC, pbzweihander commented
jotai나 recoil조차도 당장은 필요 없을 것 같다는게 제 생각입니다

2024-06-23 16:14 UTC, pbzweihander requested changes

2024-06-23 16:14 UTC, pbzweihander commented on frontend/src/pages/login/LogInIndex.tsx
> +  }, [data]);
디버그 코드가 남아있네요

2024-06-23 16:41 UTC, Squarecat-meow commented on frontend/src/pages/login/LogInIndex.tsx
> +  }, [data]);
아 깜빡했네요!

2024-06-23 16:49 UTC, Squarecat-meow commented
Redux를 도입한 이유는 API를 통해 받아온 이미지가 여러장이 되면 URL들을 관리하기 편하게 하려고 도입을 결정했었습니다. 지금 당장은 store에 URL을 넣고, 이미지를 지우면 URL을 Reset하는 간단한 구현이지만 후에 이미지 갯수가 더 많아지면 스케일링하기 용이할거라 생각했는데, 필요없다고 생각하신 이유가 궁금합니다.

2024-06-23 23:51 UTC, pbzweihander commented
음 지금 이미지가 필요한게 new chirp 컴포넌트 하나밖에 없으니까 그냥 state로 관리해도 되는 것 아닌가요...?

2024-06-23 23:53 UTC, pbzweihander commented
아 혹시 미스키마냥 다른 페이지에 갔다오거나 헀을 때도 첨부한 이미지가 남아있게 하기 위함인가요 그럼 인정

2024-06-23 23:53 UTC, pbzweihander commented
제가 사실 redux jotai recoil 다 안 써봐서 웬만하면 안 붙이려고 한 건데 흠 이정도 규모의 프로젝트면 하나쯤 붙여야할 것 같기도 하네요

2024-06-24 01:18 UTC, pbzweihander commented
함 jotai로 해보실래요?? 티르 님의 점지!!

2024-06-24 04:31 UTC, Squarecat-meow commented
jotai 정도면 useState문과 비슷하고 가볍고 타입스크립트 친화적이라고 하니 쓸만할 것 같네요!

2024-06-26 23:39 UTC, Squarecat-meow commented
todo: 이미지 업로드 취소기능, 올린 이미지를 노트 리스트에서도 볼 수 있게, 이미지 선택창 크기 정형화

2024-06-30 12:52 UTC, Squarecat-meow commented
```JS
export const File = z.object({
  //id: Id,
  mediaType: z.string(),
  url: z.string().url(),
  alt: z.string().nullish(),
});
//dto.ts
```
@pbzweihander dto.ts에 위에 주석처리한 Id는 필요한가요? 노트 목록에 이미지 보이게 하려는데 저게 있으니까 ZodError가 나오네요... 주석처리해서 없애면 잘 나옵니다

2024-07-02 06:28 UTC, pbzweihander commented
아마 백엔드 쪽에서 잘못 주고 있을거에요 제가 함 볼게요

2024-07-26 15:10 UTC, pbzweihander requested changes
main으로 리베이스 한 번 해주세요!

2024-07-26 15:10 UTC, pbzweihander commented on frontend/src/components/Images.tsx
> +//import "./Images.css";
주석은 남기지 말고 지워주시겠어요?

2024-07-26 15:10 UTC, pbzweihander commented on frontend/src/components/Images.tsx
> +    alt?: string | null | undefined;
```suggestion
    alt?: string;
```
만으로 되지 않을까요?

2024-07-26 15:10 UTC, pbzweihander commented on frontend/src/components/NewChirp/BottomNewChirp.tsx
> +    /> */}
주석 걍 지우시져

2024-07-26 15:10 UTC, pbzweihander commented on frontend/src/dto.ts
> +  //id: Id,
지우셔도 될 것 같아요

2024-07-26 15:10 UTC, pbzweihander commented on frontend/src/main.tsx
> +import { Provider } from "jotai";
```suggestion
import { Provider as JotaiProvider } from "jotai";
```
으로 바꿔주실래요? 이름이 너무 generic해서.. 아니면
```
import jotai from "jotai";
```
로 하고 `jotai.Provider` 로 쓰거나요

2024-07-27 05:22 UTC, pbzweihander approved these changes

2024-07-27 05:28 UTC, merged

2024-07-27 07:11 UTC, Squarecat-meow commented
리뷰하신거 보려고 했는데 이미 머지가 되어있네요ㅋㅋㅋㅋㅋ
감사합니다!!